name: Deploy to DigitalOcean

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Build and Deploy to DigitalOcean Droplet
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Debug npm build
      working-directory: ./skylance-dashboard
      run: |
        npm install
        npm run build

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./skylance-dashboard
        file: ./skylance-dashboard/Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/skylance-frontend-final:latest
        platforms: linux/amd64,linux/arm64
        build-args: |
          VITE_API_BASE_URL=${{ secrets.VITE_API_BASE_URL }}

    - name: SSH to DigitalOcean and Deploy
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.DROPLET_IP }}
        username: ${{ secrets.DROPLET_USER }}
        key: ${{ secrets.DROPLET_SSH_KEY }}
        script: |
          # Stop/remove old container
          docker stop skylance-frontend || true
          docker rm skylance-frontend || true

          # Pull and run new container
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/skylance-frontend-final:latest
          docker run -d --name skylance-frontend -p 3000:80 ${{ secrets.DOCKERHUB_USERNAME }}/skylance-frontend-final:latest